services:
  nodeapp:
    container_name: nodeappcontainer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/code
    ports:
      - 3000:3000
    expose:
      - 3000
# docker-compose up -d
# docker-compose down

# docker rmi $(docker images -q) 시스템상 모든 이미지를 삭제
